# rules/default.yaml
# Default set of rules for the software development planning assistant.

# --- RFC Generation Rules ---

# Defines the Markdown template structure for generated RFCs.
# Use '|' for a multi-line string.
rfc_template: |
  # RFC: [Feature Title]

  **Date:** {{CURRENT_DATE}}
  **Author:** [Your Name/AI Assistant]
  **Status:** Draft

  ## 1. Summary
  *A brief, one-paragraph explanation of the feature and the problem it solves.*

  ## 2. Goals
  * *Specific, measurable objective 1.*
  * *Specific, measurable objective 2.*

  ## 3. Non-Goals
  * *What this feature will *not* address.*

  ## 4. Technical Approach
  * *High-level overview of the implementation.*
  * *Key components affected or created.*
  * *Data model changes (if any).*
  * *API design (if applicable).*

  ## 5. Risks & Mitigation
  * *Potential technical or product risks.*
  * *How we plan to address these risks.*

  ## 6. Alternatives Considered
  * *Briefly mention other approaches and why this one was chosen.*

# --- General Development Rules ---

# Primary programming language for new backend services.
primary_language: Python 3.11+

# Code style guide to follow.
code_style: "Black for Python, Prettier for Frontend."

# Branching strategy.
branching_strategy: "GitFlow (feature/xxx, develop, main)."

# Testing policy requirements.
testing_policy: "Unit tests must cover > 80% of new code. Integration tests required for new API endpoints."

# --- Task Generation Rules ---

# Guidelines for how tasks should be prioritized.
task_prioritization: "1. Security fixes. 2. Core backend logic. 3. API endpoints. 4. Frontend UI. 5. Testing. 6. Documentation."

# Specific instructions for the AI when breaking down tasks.
task_rules: |
  - Break down features into the smallest reasonable tasks (1-3 days effort max).
  - Ensure every backend change has a corresponding testing task.
  - Create a 'Deploy & Monitor' task for significant features.
  - Prefix backend tasks with '[BE]' and frontend tasks with '[FE]'.
  - Assign high priority to tasks involving authentication or data integrity.
  - Include a task for updating documentation if APIs or major features change.

# --- Other Configurations ---

# Default assignee for tasks if not specified.
default_assignee: "Project Lead"

# JIRA project key (if applicable).
jira_project_key: "DEV"
